from pathlib import Path
import json,csv,subprocess,datetime,os
qc=Path(r"E:\chatgpt\qc_50ns"); src=Path(r"E:\chatgpt\ptger4_membrane_md_20260904")
frame=json.loads((qc/'frame_50ns.json').read_text(encoding='utf-8')); traj=json.loads((qc/'pbc_corrected_vs_minimized.json').read_text(encoding='utf-8')); thermo=json.loads((qc/'thermo_50ns.json').read_text(encoding='utf-8')); contacts=json.loads((qc/'contacts_50ns.json').read_text(encoding='utf-8'))
with (src/'production.csv').open(newline='',encoding='utf-8-sig') as f:
 rows=list(csv.reader(f))
last=next(r for r in reversed(rows) if r and not r[0].startswith('#'))
proc=subprocess.run(['powershell','-NoProfile','-Command','if(Get-Process -Id 215624 -ErrorAction SilentlyContinue){"running"}else{"stopped"}'],capture_output=True,text=True).stdout.strip()
out={'requested_ns':50.0,'trajectory_exact_frame_ns':frame['time_ps']/1000.0,'trajectory_snapshot_end_ns':traj['time_end_ps']/1000.0,'live_time_ns':float(last[1])/1000.0,'live_speed_ns_day':float(last[8]) if last[8] not in ('--','') else None,'live_remaining':last[9],'current_temperature_K':float(last[5]),'current_density_g_ml':float(last[7]),'temperature_mean_K_after_0p5ns':thermo['temperature_mean_K_after_0p5ns'],'temperature_sd_K_after_0p5ns':thermo['temperature_sd_K_after_0p5ns'],'density_mean_g_ml_after_0p5ns':thermo['density_mean_g_mL_after_0p5ns'],'density_sd_g_ml_after_0p5ns':thermo['density_sd_g_mL_after_0p5ns'],'protein_ca_rmsd_vs_minimized_A_at_50ns':frame['protein_ca_rmsd_vs_minimized_A'],'protein_ca_rmsd_vs_minimized_mean_A_through_snapshot':traj['protein_ca_rmsd_vs_minimized_mean_A'],'protein_ca_rmsd_vs_minimized_max_A_through_snapshot':traj['protein_ca_rmsd_vs_minimized_max_A'],'ligand_rmsd_pbc_corrected_vs_minimized_A_at_50ns':frame['ligand_rmsd_pbc_corrected_vs_minimized_A'],'ligand_com_displacement_A_at_50ns':frame['ligand_com_displacement_pbc_corrected_vs_minimized_A'],'ligand_rmsd_pbc_corrected_mean_A_through_snapshot':traj['ligand_rmsd_pbc_corrected_vs_minimized_mean_A'],'ligand_rmsd_pbc_corrected_max_A_through_snapshot':traj['ligand_rmsd_pbc_corrected_vs_minimized_max_A'],'ligand_com_displacement_mean_A_through_snapshot':traj['ligand_com_displacement_pbc_corrected_vs_minimized_mean_A'],'ligand_com_displacement_max_A_through_snapshot':traj['ligand_com_displacement_pbc_corrected_vs_minimized_max_A'],'ligand_contacts_4p5A_at_50ns':contacts['protein_heavy_atoms_with_ligand_within_4p5A'],'ligand_contacts_4p5A_mean_through_snapshot':traj['ligand_protein_contacts_4p5A_mean'],'ligand_contacts_4p5A_last':traj['ligand_protein_contacts_4p5A_last'],'ligand_contacts_4p5A_min':traj['ligand_protein_contacts_4p5A_min'],'ligand_contacts_4p5A_max':traj['ligand_protein_contacts_4p5A_max'],'coordinate_nonfinite':False,'process_status':proc,'recommendation':'Continue production toward 100 ns for longer-timescale sampling. The 50 ns segment is structurally stable with retained ligand contacts and no coordinate failures; this supports structural plausibility only and does not establish affinity, residence time, or causal biology.','files':{'frame_50ns':'E:/chatgpt/qc_50ns/frame_50ns.json','trajectory_qc':'E:/chatgpt/qc_50ns/pbc_corrected_vs_minimized.json','thermo_qc':'E:/chatgpt/qc_50ns/thermo_50ns.json','contacts_qc':'E:/chatgpt/qc_50ns/contacts_50ns.json','snapshot_dcd':'E:/chatgpt/qc_50ns/production.dcd','snapshot_csv':'E:/chatgpt/qc_50ns/production.csv','checkpoint':'E:/chatgpt/qc_50ns/production.chk'}}
(qc/'status_50ns.json').write_text(json.dumps(out,indent=2,ensure_ascii=False),encoding='utf-8'); print(json.dumps(out,ensure_ascii=False))
