from pathlib import Path
repo=Path(r"E:\chatgpt\whynot17"); p=repo/'outputs/md_ptger4_membrane_md/README.md'; s=p.read_text(encoding='utf-8')
needle='Temperature after the initial 0.5 ns was 310.29 ± 1.10 K and density was 1.0263 ± 0.0018 g/mL.\n'
add='''Temperature after the initial 0.5 ns was 310.29 ± 1.10 K and density was 1.0263 ± 0.0018 g/mL.\n\nA focused local-reference check over 40–70 ns (using the 40 ns frame to remove the early 0–10 ns pose relocation) found core RMSD 1.03 ± 0.38 Å (maximum 3.29 Å), COM drift 0.52 ± 0.25 Å (maximum 1.74 Å), pocket-residue contact fraction 81.1%, and a core-to-pocket nearest distance of 3.57 Å that stayed within 4.5 Å in every frame. Brief excursions were not sustained.\n\nThe minimal DINP decomposition over 0–50 ns separates a rigid aromatic ring (internal RMSD 0.046 Å) from flexible ester/alkyl arms. Relative to the minimized starting pose, the aromatic core relocates early, while the later 40–70 ns local state remains stable; whole-ligand RMSD should therefore be interpreted together with local-reference RMSD and COM/contact metrics.\n'''
if needle in s: s=s.replace(needle,add)
else: s += '\n'+add
s=s.replace('- `status_25ns.json`, `status_35ns.json`, `status_50ns.json`: milestone status records','- `status_25ns.json`, `status_35ns.json`, `status_50ns.json`, `status_40_70_local_reference.json`: milestone status records')
s=s.replace('- `qc_10ns_vs_minimized.json`, `qc_35ns_vs_minimized.json`, `qc_50ns_vs_minimized.json`: PBC-corrected trajectory summaries','- `qc_10ns_vs_minimized.json`, `qc_35ns_vs_minimized.json`, `qc_50ns_vs_minimized.json`, `status_40_70_local_reference.json`: PBC-corrected and local-reference summaries')
s=s.replace('- `qc_10ns_vs_minimized.csv`, `qc_35ns_vs_minimized.csv`, `qc_50ns_vs_minimized.csv`: per-frame RMSD and COM series','- `qc_10ns_vs_minimized.csv`, `qc_35ns_vs_minimized.csv`, `qc_50ns_vs_minimized.csv`, `qc_dinp_40_70_local_timeseries.csv`: per-frame RMSD, COM and contact series')
s=s.replace('- `qc_snapshot_1p6ns.json`, `qc_10ns_pbc_corrected_qc.json`, `frame_50ns.json`, `thermo_50ns.json`, `contacts_50ns.json`: frame and thermodynamic QC records','- `qc_snapshot_1p6ns.json`, `qc_10ns_pbc_corrected_qc.json`, `frame_50ns.json`, `thermo_50ns.json`, `contacts_50ns.json`, `thermo_40_70.json`: frame and thermodynamic QC records\n- `minimal_test_summary_0_50ns.json`, `core_internal_pocket_summary_0_50ns.json`, `minimal_test_0_50ns.png`: DINP core/branch/pocket decomposition')
p.write_text(s,encoding='utf-8')
root=repo/'README.md'; rs=root.read_text(encoding='utf-8'); rs=rs.replace('PTGER4–DINP membrane MD: 50 ns milestone QC recorded; 100 ns production continues locally','PTGER4–DINP membrane MD: 40–70 ns local-reference QC recorded; 100 ns production continues locally'); root.write_text(rs,encoding='utf-8')
