from pathlib import Path
repo=Path(r"E:\chatgpt\whynot17")
p=repo/'outputs/md_ptger4_membrane_md/README.md'
s=p.read_text(encoding='utf-8')
s=s.replace('At the time of this commit the live run had reached approximately 36.3 ns at about 63.5 ns/day.','At the time of this commit the live run had reached approximately 50.3 ns at about 62.7 ns/day; production continues toward 100 ns.')
s=s.replace('| 35.0 ns frame | 1.71 Å | 4.05 Å | 0.73 Å | 113 | No sustained contact loss or clear dissociation |','| 35.0 ns frame | 1.71 Å | 4.05 Å | 0.73 Å | 113 | No sustained contact loss or clear dissociation |\n| 50.0 ns frame | 1.54 Å | 4.66 Å | 0.33 Å | 120 | Protein stable; contacts retained; ligand remains near the starting region |')
s=s.replace('For the trajectory through 35.4 ns, protein Cα RMSD averaged 1.61 Å (maximum 2.04 Å). PBC-corrected DINP RMSD averaged 4.15 Å (maximum 5.01 Å), while the ligand COM displacement averaged 0.78 Å (maximum 2.83 Å). The 4.5 Å contact count averaged 121 (range 98–143). Temperature after the initial 0.5 ns was 310.28 ± 1.10 K and density was 1.0261 ± 0.0018 g/mL.','For the trajectory through 50.23 ns, protein Cα RMSD averaged 1.63 Å (maximum 2.04 Å). PBC-corrected DINP RMSD averaged 4.18 Å (maximum 5.01 Å), while the ligand COM displacement averaged 0.73 Å (maximum 2.83 Å). The 4.5 Å contact count averaged 122 (range 94–146); the exact 50 ns frame has 120 contacts. Temperature after the initial 0.5 ns was 310.29 ± 1.10 K and density was 1.0263 ± 0.0018 g/mL.')
s=s.replace('- `status_25ns.json`, `status_35ns.json`: milestone status records','- `status_25ns.json`, `status_35ns.json`, `status_50ns.json`: milestone status records')
s=s.replace('- `qc_10ns_vs_minimized.json`, `qc_35ns_vs_minimized.json`: PBC-corrected trajectory summaries','- `qc_10ns_vs_minimized.json`, `qc_35ns_vs_minimized.json`, `qc_50ns_vs_minimized.json`: PBC-corrected trajectory summaries')
s=s.replace('- `qc_10ns_vs_minimized.csv`, `qc_35ns_vs_minimized.csv`: per-frame RMSD and COM series','- `qc_10ns_vs_minimized.csv`, `qc_35ns_vs_minimized.csv`, `qc_50ns_vs_minimized.csv`: per-frame RMSD and COM series')
s=s.replace('- `production_state_log_to_10ns.csv`, `production_state_log_to_35ns.csv`: OpenMM thermodynamic logs','- `production_state_log_to_10ns.csv`, `production_state_log_to_35ns.csv`, `production_state_log_to_50ns.csv`: OpenMM thermodynamic logs')
s=s.replace('- `qc_snapshot_1p6ns.json`, `qc_10ns_pbc_corrected_qc.json`: earlier checkpoint and trajectory QC records','- `qc_snapshot_1p6ns.json`, `qc_10ns_pbc_corrected_qc.json`, `frame_50ns.json`, `thermo_50ns.json`, `contacts_50ns.json`: frame and thermodynamic QC records')
p.write_text(s,encoding='utf-8')
l=repo/'outputs/md_ptger4_membrane_md/live_run_status.md'
l.write_text('''# PTGER4–DINP MD run status\n\nStarted 2026-09-04 on the E: drive.\n\n- Environment: `E:\\chatgpt\\md_env` (Python 3.11, OpenMM 8.6, MDAnalysis 2.10, PDBFixer 1.12, Open Babel wheel)\n- Platform: OpenCL on NVIDIA GeForce RTX 4060 Laptop GPU, mixed precision\n- System: 73,768 atoms; POPC membrane, 310 K, 0.15 M NaCl\n- Target: 100 ns production, 2 fs timestep\n- Source checkpoint: resumed from the latest completed checkpoint at 24.1 ns after the desktop window was closed\n- Background process: PID 215624\n- Output directory: `E:\\chatgpt\\ptger4_membrane_md_20260904`\n- Live progress at this update: approximately 50.3 ns at 62.7 ns/day; about 19 hours remain to 100 ns\n\nThe runner writes a DCD frame and CSV row every 10 ps and a checkpoint every 100 ps. The 50 ns snapshot shows stable protein Cα RMSD, retained ligand contacts and no nonfinite coordinates. Stable trajectories indicate computational structural plausibility only and do not establish experimental binding or causal biology.\n''',encoding='utf-8')
root=repo/'README.md'; rs=root.read_text(encoding='utf-8'); rs=rs.replace('PTGER4–DINP membrane MD: 35 ns milestone QC recorded; 100 ns production continues locally','PTGER4–DINP membrane MD: 50 ns milestone QC recorded; 100 ns production continues locally'); root.write_text(rs,encoding='utf-8')
