from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def gasteiger_charges(off_molecule):
    """Assign RDKit Gasteiger charges so no AmberTools executable is required."""
    from rdkit import Chem
    from rdkit.Chem import AllChem
    from openff.units import unit

    rdmol = off_molecule.to_rdkit()
    Chem.rdPartialCharges.ComputeGasteigerCharges(rdmol)
    values = []
    for atom in rdmol.GetAtoms():
        try:
            values.append(float(atom.GetProp("_GasteigerCharge")))
        except (KeyError, ValueError):
            values.append(0.0)
    off_molecule.partial_charges = unit.Quantity(values, unit.elementary_charge)
    return values


def main():
    parser = argparse.ArgumentParser(description="Build explicit-solvent PPARG-DINP OpenMM system.")
    parser.add_argument("--complex-pdb", type=Path, required=True)
    parser.add_argument("--protein-pdb", type=Path, required=True)
    parser.add_argument("--ligand-sdf", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--padding-nm", type=float, default=1.0)
    parser.add_argument("--temperature-k", type=float, default=310.0)
    parser.add_argument("--ionic-strength-m", type=float, default=0.15)
    args = parser.parse_args()

    for path in (args.complex_pdb, args.protein_pdb, args.ligand_sdf):
        if not path.exists():
            raise FileNotFoundError(path)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    import openmm
    from openmm import XmlSerializer, unit as omm_unit
    from openmm.app import ForceField, Modeller, PDBFile, PME, HBonds
    from openmmforcefields.generators import SystemGenerator
    from openff.toolkit import Molecule

    # The pose SDF is generated from the docked PDB ligand.  It has the exact
    # docked heavy-atom coordinates; explicit H coordinates are generated by
    # RDKit before OpenFF parameterization.
    pose_sdf = args.out_dir / "DINP_docked_pose_h.sdf"
    from rdkit import Chem

    pose = Chem.MolFromMolFile(str(args.ligand_sdf), removeHs=False, sanitize=True)
    if pose is None:
        raise RuntimeError(f"Could not read ligand pose {args.ligand_sdf}")
    pose_h = Chem.AddHs(pose, addCoords=True)
    Chem.MolToMolFile(pose_h, str(pose_sdf))
    ligand = Molecule.from_file(str(pose_sdf), file_format="sdf", allow_undefined_stereo=True)
    charges = gasteiger_charges(ligand)

    ligand_topology = ligand.to_topology().to_openmm()
    if not ligand.conformers:
        raise RuntimeError("DINP pose has no conformer")
    # OpenFF uses Pint units while OpenMM uses its own unit class.
    ligand_positions = omm_unit.nanometer * ligand.conformers[0].to("nanometer").magnitude

    # SystemGenerator registers the OpenFF small-molecule template with the
    # Amber14 protein and TIP3P water force fields, including cross interactions.
    system_generator = SystemGenerator(
        forcefields=["amber14-all.xml", "amber14/tip3p.xml"],
        small_molecule_forcefield="openff-2.2.1",
        molecules=[ligand],
        forcefield_kwargs={
            "constraints": HBonds,
            "rigidWater": True,
            "removeCMMotion": False,
        },
        periodic_forcefield_kwargs={
            "nonbondedMethod": PME,
            "nonbondedCutoff": 1.0 * omm_unit.nanometer,
            "constraints": HBonds,
            "rigidWater": True,
            "removeCMMotion": False,
        },
    )
    protein = PDBFile(str(args.protein_pdb))
    modeller = Modeller(protein.topology, protein.positions)
    # Add protein H with the same force field that will parameterize the system.
    modeller.addHydrogens(system_generator.forcefield, pH=7.0)
    modeller.add(ligand_topology, ligand_positions)
    modeller.addSolvent(
        system_generator.forcefield,
        model="tip3p",
        padding=args.padding_nm * omm_unit.nanometer,
        ionicStrength=args.ionic_strength_m * omm_unit.molar,
        neutralize=True,
    )
    system = system_generator.create_system(modeller.topology)
    system.addForce(openmm.MonteCarloBarostat(1.0 * omm_unit.bar, args.temperature_k * omm_unit.kelvin, 25))

    # Save the validated inputs consumed by run_pparg_external_md.py.
    system_xml = args.out_dir / "system.xml"
    topology_pdb = args.out_dir / "system_topology.pdb"
    initial_pdb = args.out_dir / "initial.pdb"
    system_xml.write_text(XmlSerializer.serialize(system), encoding="utf-8")
    with topology_pdb.open("w", encoding="utf-8") as handle:
        PDBFile.writeFile(modeller.topology, modeller.positions, handle, keepIds=True)
    with initial_pdb.open("w", encoding="utf-8") as handle:
        PDBFile.writeFile(modeller.topology, modeller.positions, handle, keepIds=True)
    metadata = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "status": "system_built",
        "complex_pdb": str(args.complex_pdb),
        "protein_pdb": str(args.protein_pdb),
        "ligand_sdf": str(args.ligand_sdf),
        "ligand_pose_sdf": str(pose_sdf),
        "ligand_forcefield": "openff-2.2.1",
        "ligand_charge_method": "RDKit Gasteiger",
        "protein_forcefield": "Amber14-all / TIP3P",
        "temperature_k": args.temperature_k,
        "padding_nm": args.padding_nm,
        "ionic_strength_m": args.ionic_strength_m,
        "n_particles": system.getNumParticles(),
        "n_ligand_atoms": ligand_topology.getNumAtoms(),
        "n_topology_atoms": modeller.topology.getNumAtoms(),
        "barostat": "MonteCarloBarostat 1 bar, volume moves every 25 steps",
        "interpretation_boundary": "This system is suitable for structural stability MD; docking and MD do not establish experimental affinity or causality.",
        "gasteiger_charge_sum_e": sum(charges),
    }
    (args.out_dir / "system_build_manifest.json").write_text(json.dumps(metadata, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(metadata, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
