#!/usr/bin/env python
"""Build the Step 10A source-replacement registry and frozen source set.

This file intentionally contains only source metadata and pre-result
eligibility decisions. It does not load candidate, disease, or association
results. Any source marked conditional must pass its source-specific audit
before it can enter Step 10B.
"""

from __future__ import annotations

import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


OUT_DIR = Path(__file__).resolve().parent
REGISTRY_PATH = OUT_DIR / "STEP10_SOURCE_REPLACEMENT_REGISTRY.csv"
FROZEN_PATH = OUT_DIR / "STEP10_FROZEN_SOURCE_SET.json"
AUDIT_PATH = OUT_DIR / "STEP10A_SOURCE_FEASIBILITY_AUDIT.md"
MANIFEST_PATH = OUT_DIR / "STEP10A_SOURCE_REGISTRY_MANIFEST.json"


FIELDS = [
    "source_id",
    "source_name",
    "source_layer",
    "evidence_type",
    "entity_level",
    "human_only_possible",
    "download_api",
    "public_access",
    "version_date",
    "candidate_coverage_possible",
    "identifier_system",
    "independence_from_ctd",
    "independence_from_genecards",
    "independence_from_nhanes",
    "main_bias",
    "eligible_for_step10",
    "exclusion_reason",
    "official_reference_url",
    "frozen_role",
]


SOURCES = [
    {
        "source_id": "E1",
        "source_name": "ChEMBL",
        "source_layer": "environmental",
        "evidence_type": "measured bioactivity / compound-protein activity",
        "entity_level": "compound-protein-target",
        "human_only_possible": "yes, target organism filter",
        "download_api": "public web interface, REST API, bulk releases",
        "public_access": "public",
        "version_date": "release/version must be captured at Step 10B retrieval; rolling release",
        "candidate_coverage_possible": "yes, structure/name/CAS/PubChem/UniChem crosswalk; actual yield pending",
        "identifier_system": "ChEMBL ID, UniProt, target organism, structure identifiers",
        "independence_from_ctd": "yes, distinct curated bioactivity platform; publication overlap not assumed absent",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "drug-like and bioactive-compound ascertainment; activity is not environmental exposure or toxic effect",
        "eligible_for_step10": "pass",
        "exclusion_reason": "",
        "official_reference_url": "https://www.ebi.ac.uk/chembl/",
        "frozen_role": "primary environmental direct-activity replacement",
    },
    {
        "source_id": "E2",
        "source_name": "BindingDB",
        "source_layer": "environmental",
        "evidence_type": "measured ligand-protein affinity",
        "entity_level": "ligand-protein-target",
        "human_only_possible": "yes, protein target mapping/filter",
        "download_api": "public REST API and date-stamped TSV/SQL downloads",
        "public_access": "public",
        "version_date": "MySQL full dump listed as updated 2026-07-27; exact file/hash to capture at Step 10B",
        "candidate_coverage_possible": "yes, ligand structure/SMILES and target crosswalk; actual yield pending",
        "identifier_system": "BindingDB ligand/reaction IDs, SMILES, UniProt/PDB target IDs",
        "independence_from_ctd": "yes, distinct affinity curation; publication overlap not assumed absent",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "uneven affinity measurement, assay heterogeneity, and strong drug-discovery ascertainment",
        "eligible_for_step10": "pass",
        "exclusion_reason": "",
        "official_reference_url": "https://www.bindingdb.org/rwd/bind/BindingDBRESTfulAPI.jsp",
        "frozen_role": "primary environmental binding replacement",
    },
    {
        "source_id": "E3",
        "source_name": "PubChem BioAssay",
        "source_layer": "environmental",
        "evidence_type": "deposited bioassay activity / assay target when available",
        "entity_level": "substance-assay-readout-target",
        "human_only_possible": "conditional, assay-specific target/taxonomy fields",
        "download_api": "PUG-REST/PUG-View, web downloads, FTP/RDF",
        "public_access": "public",
        "version_date": "rolling database; AID-level deposition/modification dates and retrieval date required",
        "candidate_coverage_possible": "yes, PubChem CID/SID/AID crosswalk; actual yield pending",
        "identifier_system": "PubChem CID/SID/AID, GeneID/GeneSymbol when assay target exists",
        "independence_from_ctd": "yes architecturally; depositor/publication overlap possible",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "heterogeneous assay design and incomplete target annotation; not every assay has a gene/protein target",
        "eligible_for_step10": "pass",
        "exclusion_reason": "",
        "official_reference_url": "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest-tutorial",
        "frozen_role": "primary environmental assay-activity replacement",
    },
    {
        "source_id": "E4",
        "source_name": "EPA CompTox / ToxCast",
        "source_layer": "environmental",
        "evidence_type": "toxicology high-throughput assay activity / concentration-response",
        "entity_level": "chemical-assay-endpoint",
        "human_only_possible": "conditional, assay target/cell context specific",
        "download_api": "public CTX APIs, dashboard downloads, invitroDB downloads",
        "public_access": "public",
        "version_date": "CompTox Dashboard v2.8 (2026-03-17); bioactivity domain documented as invitroDB v4.2 (Sept 2024)",
        "candidate_coverage_possible": "yes by DTXSID/structure crosswalk; actual yield pending",
        "identifier_system": "DTXSID, CAS, InChIKey, assay and endpoint identifiers",
        "independence_from_ctd": "yes as a distinct EPA assay platform; source-level overlaps must be audited",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "in-vitro assay and endpoint heterogeneity; ToxCast/Tox21 activity is not a direct gene-interaction edge",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Retained as a toxicology activity layer, not pooled with direct chemical-gene edges until endpoint-to-gene rules are frozen.",
        "official_reference_url": "https://www.epa.gov/comptox-tools/downloadable-computational-toxicology-data",
        "frozen_role": "conditional toxicology activity corroboration",
    },
    {
        "source_id": "E5",
        "source_name": "Tox21",
        "source_layer": "environmental",
        "evidence_type": "high-throughput toxicology assay activity",
        "entity_level": "chemical-assay-endpoint",
        "human_only_possible": "conditional, assay-specific",
        "download_api": "public data through EPA/CompTox and related assay portals",
        "public_access": "public/fragmented",
        "version_date": "release and data portal snapshot must be captured at Step 10B",
        "candidate_coverage_possible": "possible by DTXSID/CID/structure crosswalk; actual yield pending",
        "identifier_system": "DTXSID/CAS/PubChem and assay-specific identifiers",
        "independence_from_ctd": "yes as a separate screening programme; source/publication overlap possible",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "screening endpoint heterogeneity, assay-specific coverage, and limited direct gene interpretation",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Not a directly comparable chemical-gene source; endpoint semantics and release packaging must be frozen first.",
        "official_reference_url": "https://www.epa.gov/comptox-tools/toxicity-forecasting-toxcast",
        "frozen_role": "conditional toxicology activity corroboration",
    },
    {
        "source_id": "E6",
        "source_name": "LINCS / L1000",
        "source_layer": "environmental",
        "evidence_type": "chemical or perturbagen-induced transcriptomic response",
        "entity_level": "perturbagen-cell-state-gene-signature",
        "human_only_possible": "conditional, cell line and perturbagen context specific",
        "download_api": "GEO-deposited data and source-specific portals",
        "public_access": "public with accession-level retrieval",
        "version_date": "accession/release and matrix hash must be captured at Step 10B",
        "candidate_coverage_possible": "possible by perturbagen name/structure crosswalk; actual yield pending",
        "identifier_system": "GEO accession, perturbagen ID/name, HGNC/Entrez gene IDs",
        "independence_from_ctd": "yes as a perturbational expression resource",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "cell-line context, dose/time dependence, and response signatures are not direct target evidence",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Kept as mechanistic directionality corroboration; not pooled with CTD target edges or affinity records.",
        "official_reference_url": "https://clue.io/connectopedia/pdf/lincs_cmap_data",
        "frozen_role": "conditional perturbational-response corroboration",
    },
    {
        "source_id": "D1",
        "source_name": "Open Targets Platform",
        "source_layer": "disease",
        "evidence_type": "integrated target-disease association evidence",
        "entity_level": "target-disease/phenotype",
        "human_only_possible": "yes, human target/disease model",
        "download_api": "public GraphQL API, web interface, downloads",
        "public_access": "public",
        "version_date": "data 26.06; API 26.6.3 observed 2026-08-28; capture API metadata and query date",
        "candidate_coverage_possible": "yes, target/disease ontology mapping; actual convergence yield pending",
        "identifier_system": "Ensembl/UniProt target IDs, EFO/ontology disease IDs",
        "independence_from_ctd": "yes at platform architecture level; upstream source overlap possible",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "integrated evidence and target-prioritisation scoring; source-component overlap and score dependence",
        "eligible_for_step10": "pass",
        "exclusion_reason": "",
        "official_reference_url": "https://api.platform.opentargets.org/",
        "frozen_role": "primary disease-knowledge replacement",
    },
    {
        "source_id": "D2",
        "source_name": "NHGRI-EBI GWAS Catalog",
        "source_layer": "disease",
        "evidence_type": "human genetic association / mapped trait locus",
        "entity_level": "variant-study-trait-mapped-gene",
        "human_only_possible": "yes, human GWAS by definition",
        "download_api": "public REST API, full TSV/FTP downloads",
        "public_access": "public",
        "version_date": "biweekly release; capture r-YYYY-MM-DD file tag; current mapping metadata recorded at retrieval",
        "candidate_coverage_possible": "yes by EFO trait and mapped-gene fields; actual convergence yield pending",
        "identifier_system": "GCST, rsID, EFO/trait ontology, Ensembl/RefSeq mapped genes",
        "independence_from_ctd": "yes as human genetic curation; publication overlap possible",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "genetic association is not exposure biology; locus-to-gene mapping and trait definition influence the gene set",
        "eligible_for_step10": "pass",
        "exclusion_reason": "",
        "official_reference_url": "https://www.ebi.ac.uk/gwas/docs/file-downloads",
        "frozen_role": "primary human-genetics disease replacement",
    },
    {
        "source_id": "D3",
        "source_name": "DisGeNET",
        "source_layer": "disease",
        "evidence_type": "curated/text-mined gene-disease association",
        "entity_level": "gene-disease",
        "human_only_possible": "yes, gene/disease records",
        "download_api": "web/API; access plan controls result scope",
        "public_access": "conditional academic access",
        "version_date": "release and access plan must be captured at Step 10B",
        "candidate_coverage_possible": "possible via disease/gene query; full-database coverage not guaranteed under free academic access",
        "identifier_system": "NCBI Gene/Ensembl, UMLS/MeSH disease identifiers",
        "independence_from_ctd": "yes at product level; literature/source overlap possible",
        "independence_from_genecards": "yes at product level",
        "independence_from_nhanes": "yes",
        "main_bias": "curated versus text-mined evidence mix and plan-dependent access; full database not openly downloadable for academic users",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Free academic access is limited to curated data/results; source scope must be fixed before it can be a complete replacement.",
        "official_reference_url": "https://support.disgenet.com/support/solutions/articles/202000089413-can-i-download-the-disgenet-database-",
        "frozen_role": "conditional disease-knowledge corroboration",
    },
    {
        "source_id": "D4",
        "source_name": "OMIM",
        "source_layer": "disease",
        "evidence_type": "curated Mendelian phenotype-gene knowledge",
        "entity_level": "gene-phenotype",
        "human_only_possible": "yes",
        "download_api": "authorized web/API access subject to terms",
        "public_access": "conditional/licensed",
        "version_date": "authorized release/snapshot required",
        "candidate_coverage_possible": "conditional; disease definition and access scope must be confirmed",
        "identifier_system": "OMIM phenotype/gene identifiers, MIM numbers, gene symbols",
        "independence_from_ctd": "yes at product level; literature overlap possible",
        "independence_from_genecards": "partial, GeneCards may display OMIM-derived content",
        "independence_from_nhanes": "yes",
        "main_bias": "Mendelian disease focus is not equivalent to common T2D genetic architecture; access/licensing constraints",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Do not use as an open primary replacement unless authorized access, release, and non-independence handling are documented.",
        "official_reference_url": "https://www.omim.org/",
        "frozen_role": "conditional high-specificity disease knowledge",
    },
    {
        "source_id": "D5",
        "source_name": "ClinVar",
        "source_layer": "disease",
        "evidence_type": "clinical variant interpretation",
        "entity_level": "variant-condition-gene",
        "human_only_possible": "yes",
        "download_api": "NCBI FTP/API/web interface",
        "public_access": "public",
        "version_date": "release/FTP snapshot required",
        "candidate_coverage_possible": "conditional; only if variant-condition evidence is intentionally used",
        "identifier_system": "Variation ID, HGVS, GeneID, condition identifiers",
        "independence_from_ctd": "yes",
        "independence_from_genecards": "partial, GeneCards may display ClinVar-derived content",
        "independence_from_nhanes": "yes",
        "main_bias": "clinical variant interpretation and rare disease emphasis; not a general common-disease gene association source",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Not directly comparable to a disease-gene enrichment set without a prespecified variant-to-gene disease rule.",
        "official_reference_url": "https://www.ncbi.nlm.nih.gov/clinvar/",
        "frozen_role": "conditional clinical-variant corroboration",
    },
    {
        "source_id": "P1",
        "source_name": "Canadian Health Measures Survey (CHMS)",
        "source_layer": "epidemiology",
        "evidence_type": "population biomonitoring and health survey",
        "entity_level": "participant-exposure-outcome-covariate",
        "human_only_possible": "yes",
        "download_api": "public documentation/summary tables; individual microdata through RDC approval",
        "public_access": "conditional controlled microdata",
        "version_date": "cycle-specific release and data-user-guide version required",
        "candidate_coverage_possible": "possible; exact analyte-by-cycle coverage and individual diabetes fields pending audit",
        "identifier_system": "cycle/participant IDs and Statistics Canada variable labels; chemical crosswalk pending",
        "independence_from_ctd": "yes",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "cross-sectional design, controlled microdata access, and cycle-specific biomarker availability",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Cannot pass until exact exposure variables, diabetes definition, covariates, weights, and access route are verified without candidate-result inspection.",
        "official_reference_url": "https://www.statcan.gc.ca/en/statistical-programs/document/5071_D5_V2",
        "frozen_role": "conditional epidemiologic replacement",
    },
    {
        "source_id": "P2",
        "source_name": "Korea National Health and Nutrition Examination Survey (KNHANES)",
        "source_layer": "epidemiology",
        "evidence_type": "population health survey and biomonitoring",
        "entity_level": "participant-exposure-outcome-covariate",
        "human_only_possible": "yes",
        "download_api": "official web portal and cycle-specific files; access terms must be checked",
        "public_access": "public/conditional by file",
        "version_date": "cycle/year and file release must be captured",
        "candidate_coverage_possible": "possible; exact chemical/metabolite panels and compatible outcome/covariate files pending audit",
        "identifier_system": "cycle/participant IDs and Korean survey variable labels; chemical crosswalk pending",
        "independence_from_ctd": "yes",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "cycle-specific laboratory panels, language/variable harmonization, and cross-sectional design",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Exact exposure panel, outcome definition, weights, and harmonization must be verified before direct replacement.",
        "official_reference_url": "https://knhanes.kdca.go.kr/knhanes/eng/main.do",
        "frozen_role": "conditional epidemiologic replacement",
    },
    {
        "source_id": "P3",
        "source_name": "HBM4EU / IPCHEM",
        "source_layer": "epidemiology",
        "evidence_type": "human biomonitoring exposure data",
        "entity_level": "study-participant-exposure",
        "human_only_possible": "yes",
        "download_api": "IPCHEM portal; individual-level access request through data platform",
        "public_access": "public metadata/aggregate; controlled individual data",
        "version_date": "portal snapshot and study-level release required",
        "candidate_coverage_possible": "possible for exposure summaries; T2D outcome/covariate linkage not established",
        "identifier_system": "study/biomarker/matrix metadata; participant identifiers controlled by data provider",
        "independence_from_ctd": "yes",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "data-provider access, heterogeneous aligned studies, and uncertain participant-level disease linkage",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Not a direct epidemiologic replacement until individual exposure, T2D outcome, covariates, and access are confirmed in the same data extract.",
        "official_reference_url": "https://ipchem.jrc.ec.europa.eu/hbm4eu_overview.html",
        "frozen_role": "conditional biomonitoring feasibility source",
    },
    {
        "source_id": "P4",
        "source_name": "Multi-Ethnic Study of Atherosclerosis (MESA)",
        "source_layer": "epidemiology",
        "evidence_type": "longitudinal cohort / biospecimen and phenotype data",
        "entity_level": "participant-exposure-outcome-covariate",
        "human_only_possible": "yes",
        "download_api": "study-specific application and controlled data access",
        "public_access": "controlled",
        "version_date": "release and approved data package required",
        "candidate_coverage_possible": "possible in principle; analyte assay and sample availability pending access audit",
        "identifier_system": "study participant IDs, assay-specific analyte labels, controlled phenotype dictionary",
        "independence_from_ctd": "yes",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "yes",
        "main_bias": "non-population-representative cohort, controlled access, and assay/ancillary-study selection",
        "eligible_for_step10": "conditional",
        "exclusion_reason": "Requires approved data access and direct verification of the relevant exposure assay plus diabetes outcome and covariates.",
        "official_reference_url": "https://www.nhlbi.nih.gov/science/multi-ethnic-study-atherosclerosis-mesa",
        "frozen_role": "conditional prospective/longitudinal replacement",
    },
    {
        "source_id": "P0",
        "source_name": "NHANES (current reference)",
        "source_layer": "epidemiology",
        "evidence_type": "population biomonitoring and health survey",
        "entity_level": "participant-exposure-outcome-covariate",
        "human_only_possible": "yes",
        "download_api": "public CDC downloads",
        "public_access": "public",
        "version_date": "cycle-specific releases; current analysis files are separately locked",
        "candidate_coverage_possible": "reference source already used; not a replacement",
        "identifier_system": "SEQN, CDC analyte variables, cycle-specific survey design variables",
        "independence_from_ctd": "yes",
        "independence_from_genecards": "yes",
        "independence_from_nhanes": "no",
        "main_bias": "cross-sectional design and current reference-source dependence",
        "eligible_for_step10": "reference_only",
        "exclusion_reason": "Anchor dataset, not an external replacement.",
        "official_reference_url": "https://www.cdc.gov/nchs/nhanes/",
        "frozen_role": "reference epidemiologic source; not an external replacement",
    },
    {
        "source_id": "C1",
        "source_name": "Step10R expanded multi-disease panel",
        "source_layer": "disease_context",
        "evidence_type": "cross-disease survey outcome",
        "entity_level": "participant-outcome",
        "human_only_possible": "yes",
        "download_api": "existing locked repository outputs",
        "public_access": "repository artifact",
        "version_date": "existing Step10R lock and commit",
        "candidate_coverage_possible": "already complete for its frozen panel",
        "identifier_system": "NHANES variables and cycle-specific survey IDs",
        "independence_from_ctd": "not applicable",
        "independence_from_genecards": "not applicable",
        "independence_from_nhanes": "no",
        "main_bias": "same population and outcome family; transportability demonstration rather than source replacement",
        "eligible_for_step10": "supplementary_only",
        "exclusion_reason": "Retain as the fourth stress-test dimension, but do not present it as foundational database replacement.",
        "official_reference_url": "https://www.cdc.gov/nchs/nhanes/",
        "frozen_role": "supplementary disease-context stress test",
    },
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    generated = datetime.now(timezone.utc).isoformat()
    with REGISTRY_PATH.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(SOURCES)

    frozen = {
        "lock_type": "STEP10A_SOURCE_REPLACEMENT_SET",
        "generated_utc": generated,
        "selection_rule": "source feasibility and evidence semantics only; no MCOP, T2D, CRC, candidate rank, association result, or pathway result inspected",
        "primary_environmental_replacements": ["E1", "E2", "E3"],
        "primary_disease_replacements": ["D1", "D2"],
        "primary_epidemiologic_replacements": [],
        "conditional_environmental_sources": ["E4", "E5", "E6"],
        "conditional_disease_sources": ["D3", "D4", "D5"],
        "conditional_epidemiologic_sources": ["P1", "P2", "P3", "P4"],
        "reference_only_sources": ["P0"],
        "supplementary_only_sources": ["C1"],
        "why_no_primary_epidemiology_source": "No candidate-independent Step 10A audit established the joint availability of a harmonizable exposure, T2D outcome, core covariates, design weights, and usable individual-level access. Conditional sources remain queued.",
        "entity_resolution_rules": {
            "chemical": "Prefer stable structure/CAS/PubChem/DTXSID/ChEMBL/BindingDB crosswalks; retain unresolved and ambiguous records explicitly.",
            "gene": "Resolve to stable human GeneID/Ensembl/UniProt with a versioned mapping table; do not merge source-specific evidence before resolution.",
            "disease": "Use source-native ontology identifiers and a frozen T2D concept mapping; retain direct versus descendant trait matches separately.",
            "participant": "Require source-native participant ID, exposure, outcome, core covariates, and design variables in the same approved extract.",
        },
        "success_criteria": {
            "environmental": "At least two primary replacement sources yield versioned, human-compatible, entity-resolved records on the same chemical unit; report coverage, overlap, rank/edge concordance, and missingness.",
            "disease": "Both primary disease replacements yield a predeclared T2D gene set with versioned ontology mapping and source-specific evidence fields.",
            "epidemiology": "A source is promoted from conditional only after exposure, T2D outcome, core covariates, design variables, access, and chemical harmonization are verified without inspecting association results.",
            "overall": "No candidate is promoted or demoted from the frozen set solely because a replacement source agrees or disagrees with an observed association.",
        },
    }
    FROZEN_PATH.write_text(json.dumps(frozen, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    manifest = {
        "lock_type": "STEP10A_SOURCE_REGISTRY_MANIFEST",
        "generated_utc": generated,
        "registry_rows": len(SOURCES),
        "by_layer": {
            layer: sum(row["source_layer"] == layer for row in SOURCES)
            for layer in sorted({row["source_layer"] for row in SOURCES})
        },
        "by_status": {
            status: sum(row["eligible_for_step10"] == status for row in SOURCES)
            for status in sorted({row["eligible_for_step10"] for row in SOURCES})
        },
        "outcome_information_used_for_source_selection": False,
        "candidate_results_loaded": False,
        "outputs": {
            REGISTRY_PATH.name: sha256(REGISTRY_PATH),
            FROZEN_PATH.name: sha256(FROZEN_PATH),
        },
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
