#!/usr/bin/env python3
"""PTGER4–DINP membrane molecular-dynamics pipeline (OpenMM).

Purpose
-------
Run a publication-oriented first-pass 100 ns membrane MD simulation for the
PTGER4–DINP docking lead after the validated 9JQZ control-docking step.

Key design choices
------------------
* PTGER4 is a GPCR, so the simulation is built in a POPC bilayer, not in a
  soluble-protein-only water box.
* The starting ligand coordinates come from the validated PTGER4 DINP docking
  pose generated by ``run_ptger4_control_docking.py`` / rescue docking.
* Protein/lipid/water use AMBER14 ff14SB + Lipid17 + TIP3P.
* DINP is parameterized with GAFF2 through openmmforcefields/OpenFF.
* The script refuses to silently assume membrane orientation.  Supply an
  oriented PTGER4 PDB with ``--oriented-pdb`` OR explicitly acknowledge that
  the existing 9JQZ chain-A coordinates are already correctly oriented with
  ``--accept-existing-orientation``.
* Production default: 100 ns, 2 fs timestep, 310 K, 1 bar, PME, 0.15 M NaCl.
* Checkpoints and reporters make the run resumable.

This is structural plausibility work.  MD stability does not prove experimental
binding affinity or biological causality.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
from typing import Dict, Iterable, List, Optional, Tuple

ROOT = Path(__file__).resolve().parent
STAGE2 = ROOT / "outputs" / "stage2_docking"
REFINE = ROOT / "outputs" / "stage2_refine_and_rescue"
CONTROL = ROOT / "outputs" / "ptger4_control_docking"
OUT = ROOT / "outputs" / "ptger4_membrane_md"
RUNTIME = Path(r"D:\whynot17\dinp_stage2_runtime")


def save_json(obj, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False), encoding="utf-8")


def find_existing(paths: Iterable[Path]) -> Path:
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError("None of the expected files exists:\n" + "\n".join(map(str, paths)))


def prepend_runtime_path():
    candidates = [
        RUNTIME,
        RUNTIME / "Scripts",
        RUNTIME / "bin",
        RUNTIME / "Library" / "bin",
    ]
    existing = [str(p) for p in candidates if p.exists()]
    os.environ["PATH"] = os.pathsep.join(existing + [os.environ.get("PATH", "")])


def which(names: Iterable[str]) -> Optional[str]:
    for name in names:
        p = shutil.which(name)
        if p:
            return p
    return None


def run(cmd: List[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, text=True, capture_output=True, check=False)


def dependency_report() -> Dict[str, object]:
    report: Dict[str, object] = {
        "python": sys.executable,
        "openmm": False,
        "openff_toolkit": False,
        "openmmforcefields": False,
        "pdbfixer": False,
        "mdanalysis": False,
        "obabel": which(["obabel.exe", "obabel", "babel.exe", "babel"]),
    }
    try:
        import openmm  # noqa: F401
        report["openmm"] = True
        report["openmm_version"] = getattr(openmm, "__version__", "unknown")
    except Exception as exc:
        report["openmm_error"] = repr(exc)
    try:
        import openff.toolkit  # noqa: F401
        report["openff_toolkit"] = True
    except Exception as exc:
        report["openff_toolkit_error"] = repr(exc)
    try:
        import openmmforcefields  # noqa: F401
        report["openmmforcefields"] = True
    except Exception as exc:
        report["openmmforcefields_error"] = repr(exc)
    try:
        import pdbfixer  # noqa: F401
        report["pdbfixer"] = True
    except Exception as exc:
        report["pdbfixer_error"] = repr(exc)
    try:
        import MDAnalysis  # noqa: F401
        report["mdanalysis"] = True
    except Exception as exc:
        report["mdanalysis_error"] = repr(exc)
    return report


def convert_ligand(obabel: str, pdbqt: Path, outdir: Path) -> Tuple[Path, Path]:
    """Convert the first Vina pose to SDF (chemistry) and PDB (OpenMM coords)."""
    outdir.mkdir(parents=True, exist_ok=True)
    sdf = outdir / "DINP_docked_pose.sdf"
    pdb = outdir / "DINP_docked_pose.pdb"
    for out in (sdf, pdb):
        cp = run([obabel, str(pdbqt), "-O", str(out), "-f", "1", "-l", "1"])
        (outdir / f"obabel_{out.suffix[1:]}.log").write_text(
            cp.stdout + "\n" + cp.stderr, encoding="utf-8"
        )
        if cp.returncode != 0 or not out.exists() or out.stat().st_size == 0:
            raise RuntimeError(f"OpenBabel conversion failed for {out.name}")
    return sdf, pdb


def prepare_protein(input_pdb: Path, output_pdb: Path) -> Dict[str, object]:
    """Repair only missing atoms in existing residues; do not invent missing loops."""
    from pdbfixer import PDBFixer
    from openmm.app import PDBFile

    fixer = PDBFixer(filename=str(input_pdb))
    fixer.findMissingResidues()
    missing_residues = {
        str(k): [str(x) for x in v] for k, v in fixer.missingResidues.items()
    }
    # Deliberately refuse to model unresolved residues/loops automatically.
    fixer.missingResidues = {}
    fixer.findMissingAtoms()
    missing_atoms = {
        str(res): [atom.name for atom in atoms]
        for res, atoms in fixer.missingAtoms.items()
    }
    fixer.addMissingAtoms()
    output_pdb.parent.mkdir(parents=True, exist_ok=True)
    with output_pdb.open("w", encoding="utf-8") as fh:
        PDBFile.writeFile(fixer.topology, fixer.positions, fh, keepIds=True)
    return {
        "input": str(input_pdb),
        "output": str(output_pdb),
        "missing_residues_not_built": missing_residues,
        "missing_atoms_repaired": missing_atoms,
    }


def load_openff_molecule(sdf_path: Path):
    from openff.toolkit import Molecule

    mol = Molecule.from_file(str(sdf_path), allow_undefined_stereo=True)
    if isinstance(mol, list):
        if len(mol) != 1:
            raise RuntimeError(f"Expected one DINP molecule, found {len(mol)}")
        mol = mol[0]
    mol.name = "DINP"
    return mol


def build_system(
    protein_pdb: Path,
    ligand_pdb: Path,
    ligand_sdf: Path,
    outdir: Path,
    membrane_padding_nm: float,
    ionic_strength_m: float,
    temperature_k: float,
) -> Dict[str, object]:
    """Build PTGER4 + docked DINP + POPC + water + ions and parameterize."""
    from openmm import unit
    from openmm.app import ForceField, Modeller, PDBFile, PME, HBonds
    from openmmforcefields.generators import GAFFTemplateGenerator

    protein = PDBFile(str(protein_pdb))
    ligand_pdbfile = PDBFile(str(ligand_pdb))
    ligand_mol = load_openff_molecule(ligand_sdf)

    # amber14-all.xml includes ff14SB and Lipid17; the amber14 TIP3P file also
    # supplies compatible monovalent ion parameters.
    forcefield = ForceField("amber14-all.xml", "amber14/tip3p.xml")
    gaff = GAFFTemplateGenerator(
        molecules=ligand_mol,
        forcefield="gaff-2.11",
        cache=str(outdir / "gaff_cache.json"),
    )
    forcefield.registerTemplateGenerator(gaff.generator)

    modeller = Modeller(protein.topology, protein.positions)
    modeller.add(ligand_pdbfile.topology, ligand_pdbfile.positions)

    # Add hydrogens before membrane construction at near-physiological pH.
    modeller.addHydrogens(forcefield, pH=7.4)

    # OpenMM addMembrane places the membrane in XY and assumes the protein is
    # already correctly oriented with the membrane normal along Z.
    modeller.addMembrane(
        forcefield,
        lipidType="POPC",
        minimumPadding=membrane_padding_nm * unit.nanometer,
        ionicStrength=ionic_strength_m * unit.molar,
        positiveIon="Na+",
        negativeIon="Cl-",
    )

    system = forcefield.createSystem(
        modeller.topology,
        nonbondedMethod=PME,
        nonbondedCutoff=1.0 * unit.nanometer,
        constraints=HBonds,
        rigidWater=True,
        ewaldErrorTolerance=5e-4,
    )

    # Semi-isotropic membrane barostat: XY area and Z can fluctuate separately.
    # Supported by modern OpenMM.  Fall back to isotropic MonteCarloBarostat only
    # if membrane barostat is unavailable in the local build.
    import openmm
    try:
        barostat = openmm.MonteCarloMembraneBarostat(
            1.0 * unit.bar,
            0.0 * unit.bar * unit.nanometer,
            temperature_k * unit.kelvin,
            openmm.MonteCarloMembraneBarostat.XYIsotropic,
            openmm.MonteCarloMembraneBarostat.ZFree,
            25,
        )
        barostat_kind = "MonteCarloMembraneBarostat"
    except Exception:
        barostat = openmm.MonteCarloBarostat(
            1.0 * unit.bar, temperature_k * unit.kelvin, 25
        )
        barostat_kind = "MonteCarloBarostat_fallback"
    system.addForce(barostat)

    system_xml = outdir / "system.xml"
    system_xml.write_text(openmm.XmlSerializer.serialize(system), encoding="utf-8")
    built_pdb = outdir / "system_built.pdb"
    with built_pdb.open("w", encoding="utf-8") as fh:
        PDBFile.writeFile(modeller.topology, modeller.positions, fh, keepIds=True)

    counts: Dict[str, int] = {}
    for residue in modeller.topology.residues():
        counts[residue.name] = counts.get(residue.name, 0) + 1

    return {
        "modeller": modeller,
        "system": system,
        "forcefield": forcefield,
        "ligand_molecule": ligand_mol,
        "barostat": barostat_kind,
        "residue_counts": counts,
        "n_atoms": modeller.topology.getNumAtoms(),
        "built_pdb": str(built_pdb),
        "system_xml": str(system_xml),
    }


def choose_platform(requested: str):
    import openmm

    candidates = [requested] if requested != "auto" else ["CUDA", "OpenCL", "HIP", "CPU"]
    errors = {}
    for name in candidates:
        try:
            platform = openmm.Platform.getPlatformByName(name)
            props = {}
            if name in {"CUDA", "OpenCL", "HIP"}:
                props["Precision"] = "mixed"
            return platform, props, name
        except Exception as exc:
            errors[name] = repr(exc)
    raise RuntimeError(f"No requested OpenMM platform available: {errors}")


def run_md(
    built: Dict[str, object],
    outdir: Path,
    temperature_k: float,
    timestep_fs: float,
    equilibration_ns: float,
    production_ns: float,
    report_ps: float,
    checkpoint_ps: float,
    platform_name: str,
    resume: bool,
) -> Dict[str, object]:
    import openmm
    from openmm import unit
    from openmm.app import (
        CheckpointReporter,
        DCDReporter,
        PDBFile,
        Simulation,
        StateDataReporter,
    )

    modeller = built["modeller"]
    system = built["system"]

    integrator = openmm.LangevinMiddleIntegrator(
        temperature_k * unit.kelvin,
        1.0 / unit.picosecond,
        timestep_fs * unit.femtoseconds,
    )
    platform, props, chosen = choose_platform(platform_name)
    simulation = Simulation(modeller.topology, system, integrator, platform, props)

    checkpoint = outdir / "production.chk"
    log = outdir / "production.csv"
    dcd = outdir / "production.dcd"

    steps_per_ps = int(round(1000.0 / timestep_fs))
    report_steps = max(1, int(round(report_ps * steps_per_ps)))
    checkpoint_steps = max(1, int(round(checkpoint_ps * steps_per_ps)))
    equil_steps = int(round(equilibration_ns * 1000.0 * steps_per_ps))
    production_steps = int(round(production_ns * 1000.0 * steps_per_ps))

    resumed = False
    if resume and checkpoint.exists():
        simulation.loadCheckpoint(str(checkpoint))
        resumed = True
    else:
        simulation.context.setPositions(modeller.positions)
        simulation.minimizeEnergy(maxIterations=5000)
        state = simulation.context.getState(getPositions=True, getEnergy=True)
        with (outdir / "minimized.pdb").open("w", encoding="utf-8") as fh:
            PDBFile.writeFile(modeller.topology, state.getPositions(), fh, keepIds=True)
        simulation.context.setVelocitiesToTemperature(temperature_k * unit.kelvin)
        if equil_steps > 0:
            simulation.step(equil_steps)
        eq_state = simulation.context.getState(getPositions=True, getVelocities=True)
        with (outdir / "equilibrated.pdb").open("w", encoding="utf-8") as fh:
            PDBFile.writeFile(modeller.topology, eq_state.getPositions(), fh, keepIds=True)

    # Append reporters after equilibration.  If resuming, append the state log.
    simulation.reporters.append(DCDReporter(str(dcd), report_steps, append=resumed and dcd.exists()))
    simulation.reporters.append(
        StateDataReporter(
            str(log),
            report_steps,
            step=True,
            time=True,
            potentialEnergy=True,
            kineticEnergy=True,
            totalEnergy=True,
            temperature=True,
            volume=True,
            density=True,
            speed=True,
            remainingTime=True,
            totalSteps=production_steps,
            separator=",",
            append=resumed and log.exists(),
        )
    )
    simulation.reporters.append(CheckpointReporter(str(checkpoint), checkpoint_steps))

    t0 = time.time()
    simulation.step(production_steps)
    elapsed_s = time.time() - t0
    final_state = simulation.context.getState(getPositions=True, getEnergy=True)
    with (outdir / "final.pdb").open("w", encoding="utf-8") as fh:
        PDBFile.writeFile(modeller.topology, final_state.getPositions(), fh, keepIds=True)
    simulation.saveCheckpoint(str(checkpoint))

    return {
        "platform": chosen,
        "platform_properties": props,
        "resumed": resumed,
        "timestep_fs": timestep_fs,
        "equilibration_ns": equilibration_ns,
        "production_ns": production_ns,
        "production_steps": production_steps,
        "report_ps": report_ps,
        "checkpoint_ps": checkpoint_ps,
        "elapsed_seconds": elapsed_s,
        "dcd": str(dcd),
        "checkpoint": str(checkpoint),
        "log": str(log),
    }


def basic_trajectory_analysis(topology_pdb: Path, trajectory_dcd: Path, outdir: Path) -> Dict[str, object]:
    """Optional MDAnalysis post-run QC: protein CA RMSD, ligand RMSD, contacts."""
    try:
        import MDAnalysis as mda
        from MDAnalysis.analysis import rms
        import numpy as np
    except Exception as exc:
        return {"status": "skipped", "reason": f"MDAnalysis unavailable: {exc!r}"}

    u = mda.Universe(str(topology_pdb), str(trajectory_dcd))
    protein_ca = u.select_atoms("protein and name CA")
    ligand = u.select_atoms("resname UNL DINP LIG")
    if ligand.n_atoms == 0:
        # Last-resort: choose the nonprotein/nonlipid/nonwater organic residue.
        excluded = "protein or resname POPC HOH WAT TIP3 NA CL Na+ Cl-"
        ligand = u.select_atoms(f"not ({excluded})")

    result: Dict[str, object] = {
        "status": "ok",
        "n_frames": len(u.trajectory),
        "protein_ca_atoms": protein_ca.n_atoms,
        "ligand_atoms": ligand.n_atoms,
    }
    if protein_ca.n_atoms > 0:
        r = rms.RMSD(u, u, select="protein and name CA", ref_frame=0).run()
        arr = r.results.rmsd[:, [1, 2]]
        np.savetxt(outdir / "protein_ca_rmsd.csv", arr, delimiter=",", header="time_ps,rmsd_A", comments="")
        result["protein_ca_rmsd_mean_A"] = float(np.mean(arr[:, 1]))
        result["protein_ca_rmsd_last_A"] = float(arr[-1, 1])

    if ligand.n_atoms > 0:
        # Align every frame on protein C-alpha, then calculate ligand heavy-atom
        # RMSD to the first production frame.  This is a pocket-stability metric.
        from MDAnalysis.analysis import align
        ref = mda.Universe(str(topology_pdb), str(trajectory_dcd))
        align.AlignTraj(u, ref, select="protein and name CA", in_memory=True).run()
        ref.trajectory[0]
        lig_ref = ref.select_atoms(ligand.selection).positions.copy() if ligand.selection else None
        if lig_ref is not None and len(lig_ref) == ligand.n_atoms:
            rows = []
            for ts in u.trajectory:
                x = ligand.positions
                # Direct RMSD after protein alignment; atom order is preserved.
                val = math.sqrt(float(((x - lig_ref) ** 2).sum(axis=1).mean()))
                rows.append((float(ts.time), val))
            arr = np.asarray(rows)
            np.savetxt(outdir / "ligand_rmsd.csv", arr, delimiter=",", header="time_ps,rmsd_A", comments="")
            result["ligand_rmsd_mean_A"] = float(np.mean(arr[:, 1]))
            result["ligand_rmsd_last_A"] = float(arr[-1, 1])

        # Contact occupancy: protein heavy atoms within 4.5 A of DINP.
        contact_frames: Dict[Tuple[int, str, str], int] = {}
        nframes = 0
        u.trajectory.rewind()
        for ts in u.trajectory:
            nframes += 1
            near = u.select_atoms(
                f"protein and not name H* and around 4.5 ({ligand.selection})",
                updating=False,
            ) if ligand.selection else None
            if near is None:
                continue
            seen = set()
            for atom in near:
                key = (int(atom.resid), str(atom.resname), str(atom.name))
                seen.add(key)
            for key in seen:
                contact_frames[key] = contact_frames.get(key, 0) + 1
        if nframes > 0 and contact_frames:
            rows = sorted(
                [(resid, resname, atom, count / nframes) for (resid, resname, atom), count in contact_frames.items()],
                key=lambda x: x[3], reverse=True,
            )
            with (outdir / "protein_ligand_contact_occupancy.csv").open("w", encoding="utf-8") as fh:
                fh.write("resid,resname,atom,occupancy\n")
                for row in rows:
                    fh.write(f"{row[0]},{row[1]},{row[2]},{row[3]:.6f}\n")
            result["top_contact_atoms"] = rows[:20]

    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--oriented-pdb", type=Path, default=None,
                    help="PTGER4 PDB already oriented with membrane normal along Z")
    ap.add_argument("--accept-existing-orientation", action="store_true",
                    help="Explicitly accept the current 9JQZ chain-A orientation")
    ap.add_argument("--production-ns", type=float, default=100.0)
    ap.add_argument("--equilibration-ns", type=float, default=1.0)
    ap.add_argument("--temperature-k", type=float, default=310.0)
    ap.add_argument("--timestep-fs", type=float, default=2.0)
    ap.add_argument("--ionic-strength-m", type=float, default=0.15)
    ap.add_argument("--membrane-padding-nm", type=float, default=1.0)
    ap.add_argument("--report-ps", type=float, default=10.0)
    ap.add_argument("--checkpoint-ps", type=float, default=100.0)
    ap.add_argument("--platform", default="auto", choices=["auto", "CUDA", "OpenCL", "HIP", "CPU", "Reference"])
    ap.add_argument("--resume", action="store_true")
    ap.add_argument("--dry-run", action="store_true", help="Check inputs/dependencies only")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    prepend_runtime_path()

    deps = dependency_report()
    save_json(deps, OUT / "dependency_report.json")
    required = ["openmm", "openff_toolkit", "openmmforcefields", "pdbfixer"]
    missing = [x for x in required if not deps.get(x)]
    if missing:
        raise RuntimeError(
            "Missing required MD dependencies: " + ", ".join(missing) +
            ". See outputs/ptger4_membrane_md/dependency_report.json"
        )
    if not deps.get("obabel"):
        raise RuntimeError("OpenBabel executable not found")

    default_protein = find_existing([
        REFINE / "ptger4_rescue" / "PTGER4_9JQZ_chainA_clean.pdb",
        CONTROL / "PTGER4_9JQZ_chainA_clean.pdb",
    ])
    dinp_pose = find_existing([
        CONTROL / "DINP_PTGER4_pose.pdbqt",
        CONTROL / "DINP_PTGER4_9JQZ_pose.pdbqt",
        REFINE / "ptger4_rescue" / "DINP_PTGER4_9JQZ_rescue_pose.pdbqt",
    ])

    if args.oriented_pdb is not None:
        if not args.oriented_pdb.exists():
            raise FileNotFoundError(args.oriented_pdb)
        protein_input = args.oriented_pdb
        orientation_source = "user_supplied_oriented_pdb"
    elif args.accept_existing_orientation:
        protein_input = default_protein
        orientation_source = "explicitly_accepted_existing_9JQZ_orientation"
    else:
        raise RuntimeError(
            "PTGER4 is a membrane GPCR. OpenMM addMembrane assumes the protein is already oriented. "
            "Supply --oriented-pdb <OPM/PPM-oriented PTGER4.pdb> (preferred), or explicitly use "
            "--accept-existing-orientation after manually verifying that the 9JQZ membrane normal is Z."
        )

    setup = {
        "protein_input": str(protein_input),
        "orientation_source": orientation_source,
        "dinp_docking_pose": str(dinp_pose),
        "production_ns": args.production_ns,
        "equilibration_ns": args.equilibration_ns,
        "temperature_k": args.temperature_k,
        "timestep_fs": args.timestep_fs,
        "ionic_strength_m": args.ionic_strength_m,
        "membrane": "POPC",
        "protein_forcefield": "AMBER14 ff14SB",
        "lipid_forcefield": "Lipid17",
        "water": "TIP3P",
        "ligand_forcefield": "GAFF 2.11 / AM1-BCC via AmberTools",
        "interpretation_boundary": "MD stability is computational structural plausibility, not experimental binding or causality.",
    }
    save_json(setup, OUT / "setup_manifest.json")

    if args.dry_run:
        print(json.dumps({"status": "dry_run_ok", **setup, "dependencies": deps}, indent=2, ensure_ascii=False))
        return

    ligand_dir = OUT / "ligand"
    ligand_sdf, ligand_pdb = convert_ligand(str(deps["obabel"]), dinp_pose, ligand_dir)

    protein_prepared = OUT / "PTGER4_prepared.pdb"
    repair_audit = prepare_protein(protein_input, protein_prepared)
    save_json(repair_audit, OUT / "protein_repair_audit.json")

    built = build_system(
        protein_prepared,
        ligand_pdb,
        ligand_sdf,
        OUT,
        args.membrane_padding_nm,
        args.ionic_strength_m,
        args.temperature_k,
    )
    build_audit = {
        "n_atoms": built["n_atoms"],
        "barostat": built["barostat"],
        "residue_counts": built["residue_counts"],
        "built_pdb": built["built_pdb"],
        "system_xml": built["system_xml"],
    }
    save_json(build_audit, OUT / "build_audit.json")

    md = run_md(
        built,
        OUT,
        args.temperature_k,
        args.timestep_fs,
        args.equilibration_ns,
        args.production_ns,
        args.report_ps,
        args.checkpoint_ps,
        args.platform,
        args.resume,
    )
    save_json(md, OUT / "md_run_audit.json")

    analysis = basic_trajectory_analysis(
        Path(str(built["built_pdb"])), Path(md["dcd"]), OUT
    )
    save_json(analysis, OUT / "trajectory_qc.json")

    summary = [
        "# PTGER4–DINP membrane MD summary",
        "",
        f"- Membrane: POPC",
        f"- Temperature: {args.temperature_k:.1f} K",
        f"- Ionic strength: {args.ionic_strength_m:.3f} M",
        f"- Equilibration: {args.equilibration_ns:.3f} ns",
        f"- Production: {args.production_ns:.3f} ns",
        f"- Timestep: {args.timestep_fs:.3f} fs",
        f"- Platform: {md['platform']}",
        f"- Atom count: {built['n_atoms']}",
        f"- Orientation source: {orientation_source}",
        f"- Trajectory QC: {analysis.get('status')}",
    ]
    if analysis.get("ligand_rmsd_mean_A") is not None:
        summary.append(f"- DINP mean ligand RMSD: {analysis['ligand_rmsd_mean_A']:.3f} Å")
        summary.append(f"- DINP final ligand RMSD: {analysis['ligand_rmsd_last_A']:.3f} Å")
    if analysis.get("protein_ca_rmsd_mean_A") is not None:
        summary.append(f"- PTGER4 mean Cα RMSD: {analysis['protein_ca_rmsd_mean_A']:.3f} Å")
    summary += [
        "",
        "Interpretation boundary: stable MD supports dynamic structural plausibility only; it does not establish experimental binding affinity or a causal DINP–PTGER4 mechanism.",
    ]
    (OUT / "summary.md").write_text("\n".join(summary), encoding="utf-8")
    print("\n".join(summary))


if __name__ == "__main__":
    main()
